services:
  - type: web
    name: vacancies-monitoring-api
    runtime: docker
    plan: free
    dockerfilePath: apps/api/Dockerfile
    buildFilter:
      paths:
        - apps/api/**
  - type: web
    name: vacancies-monitoring-web
    runtime: docker
    plan: free
    dockerfilePath: apps/web/Dockerfile
    buildFilter:
      paths:
        - apps/web/**
